import TLanguage from "../database/TLanguage";
import TTranslationAndExamples from "../database/TTranslationAndExamples";
import TStory from "../database/TStory";
import TSong from "../database/TSong";
import { getApiUrl } from "./ApiConfig";

export type TAiQuizResponseEvaluation = {
  correctness: 'Correct' | 'Partial' | 'Wrong';
  info: string | null;
}

export default class Bot {

  /**
   * Generate a bot response to a user's message in a conversation.
   * 
   * @param user_message The message to respond to.
   * @param language The language to respond in.
   * @param user_skill The skill level of the user, either 'Beginner' or 'Intermediate'.
   * @param user_gender Whether the user is a man or a woman. Used for latin languages where gender matters.
   * @param past_messages The conversation history, exluding the message to respond to.
   * @returns The AI-generated bot response.
   */
  public static async GetBotResponseToMessage(
    user_message: string,
    language: TLanguage,
    user_skill: 'Beginner' | 'Intermediate',
    user_gender: 'Woman' | 'Man',
    past_messages: Array<{ content: string, is_bot: boolean }>
  ): Promise<string> {
    const response = await fetch(getApiUrl('/api/bot/chat'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        user_message,
        language,
        user_skill,
        user_gender,
        past_messages,
      }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.text();
  }

  /**
   * Generate a translation and two example sentences for a word in a given language.
   * 
   * @param word The word to translate and generate two example sentences for. 
   * @param language The language the word is in. Will be translated to English.
   * @returns The translation and two example sentences. TTranslationAndExamples
   */
  public static async GenerateTranslationAndExamplesForWord(word: string, language: TLanguage): Promise<TTranslationAndExamples> {
    const response = await fetch(getApiUrl('/api/bot/translate-word'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ word, language }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.json();
  }

  /**
   * Generate an English translation for a message in a given language.
   * 
   * @param message The message in `language` to translate to Englush.
   * @param language The language the message is in. 
   * @returns The English translation of the message.
   */
  public static async GenerateMessageTranslation(message: string, language: TLanguage): Promise<string> {
    const response = await fetch(getApiUrl('/api/bot/translate-message'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message, language }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.text();
  }

  /**
   * Perform a grammar and spelling check on a message in a given language,
   * returning the amount of mistakes and the corrected message.
   * 
   * @param message The message to check for grammar and spelling mistakes.
   * @param language The language the message is in.
   * @returns The amount of mistakes contained in the message and the corrected message.
   */
  public static async PerformGrammarAndSpellingCheck(message: string, language: TLanguage): Promise<{ mistake_count: number, corrected_message: string }> {
    const response = await fetch(getApiUrl('/api/bot/grammar-check'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message, language }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    const { corrected_message } = await response.json();
    const mistake_count = this.GetMistakeCount(message, corrected_message);
    return { mistake_count, corrected_message };
  }

  /**
   * Get the amount of mistakes between the original string had, given the corrected string from the AI.
   * 
   * @param original The original string.
   * @param corrected The corrected string (generated by gpt AI).
   * @returns The amount of mistakes the original string had.
   */
  private static GetMistakeCount(original: string, corrected: string): number {
    // Does not strip the hyphen (-) because it is used in compound words.
    const strip_punctuation = (str: string) => str.replace(/[\.\,\/\\\#\!\?\$\%\^\&\*\;\:\{\}\=\_\`\~\(\)\¡\¿\"\”]/g, '');
    const strip_diactritics = (str: string) => str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');

    // Split both strings into word arrays
    const originalWords = original.split(' ');
    const correctedWords = corrected.split(' ');

    // Initialize the DP table
    const dp: number[][] = Array.from({ length: originalWords.length + 1 }, () =>
        Array(correctedWords.length + 1).fill(0)
    );

    // Base cases for transformations
    for (let i = 0; i <= originalWords.length; i++) dp[i][0] = i; // cost of deletions
    for (let j = 0; j <= correctedWords.length; j++) dp[0][j] = j; // cost of insertions

    // Fill the DP table with the minimum edit distance values
    for (let i = 1; i <= originalWords.length; i++) {
        for (let j = 1; j <= correctedWords.length; j++) {
            // Strip punctuation and diacritics, and compare words
            const originalWord = strip_punctuation(strip_diactritics(originalWords[i - 1].toLowerCase())).trim();
            const correctedWord = strip_punctuation(strip_diactritics(correctedWords[j - 1].toLowerCase())).trim();

            const cost = originalWord === correctedWord ? 0 : 1;

            dp[i][j] = Math.min(
                dp[i - 1][j] + 1,    // Deletion
                dp[i][j - 1] + 1,    // Insertion
                dp[i - 1][j - 1] + cost // Substitution
            );
        }
    }

    // Return the edit distance between the two strings
    return dp[originalWords.length][correctedWords.length];
  }

  /**
   * Generate a short story that follows the given `synopsis` in `language` with AI.
   * 
   * @param language The language the story should be in
   * @param synopsis Frame for the story. The story will adhere to the synopsis.
   * @returns The generated story language, title, and body
   */
  public static async GenerateStory(language: TLanguage, synopsis: string): Promise<Omit<TStory, 'id'>> {
    console.log(`GENERATING STORY IN ${language} ON: ${synopsis}`);
    const response = await fetch(getApiUrl('/api/bot/generate-story'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ language, synopsis }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.json();
  }

  /**
   * Translate a lyric using AI and generate a meaning for the lyric.
   * @param lyric The lyric to translate into `language`. One line from the given `song`.
   * @returns The translation and meaning of the lyric.
   */
  public static async GenerateLyricTranslationAndMeaning(lyric: string, language: TLanguage, song: TSong, full_lyrics: string): Promise<{ translation: string, meaning: string }> {
    const cleanLyric = (lyric || '').replace(/\r/g, '');
    const cleanFullLyrics = (full_lyrics || '').replace(/\r/g, '');
    const response = await fetch(getApiUrl('/api/bot/lyric-translation'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ lyric: cleanLyric, language, song, full_lyrics: cleanFullLyrics }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.json();
  }

  /**
   * Translate a message from English to the given `language` with AI.
   * @param message The message in English to translate to `language`
   * @param language The language to translate to. 
   * @returns The translation of the English message in `language`.
   */
  public static async TranslateEnglishToLanguage(message: string, language: TLanguage): Promise<string> {
    const response = await fetch(getApiUrl('/api/bot/translate-english'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ message, language }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.text();
  }

  public static async IsQuizResponseCorrect(foreignWord: string, foreignLanguage: TLanguage, userTranslation: string): Promise<TAiQuizResponseEvaluation> {
    const response = await fetch(getApiUrl('/api/bot/evaluate-quiz'), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ foreignWord, foreignLanguage, userTranslation }),
    });

    if (!response.ok) {
      throw new Error(await response.text());
    }

    return await response.json();
  }
}
